name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore
    - name: Build Release
      run: dotnet build --no-restore -c Release
      
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Test Debug
        run: dotnet test --verbosity normal
      - name: Test Release
        run: dotnet test -c Release --verbosity normal

  end-to-end-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build Release
        run: dotnet build -c Release
      - name: Download DISTOD
        run: curl -L https://github.com/CodeLionX/distod/releases/download/v1.0.6/distod-1.0.6.jar > ./testdata/ci/distod.jar
      - name: Install Python dependencies
        run: pip3 install -r ./scripts/requirements.txt
      - name: Generate random example
        run: python3 ./scripts/generate-data.py -o ./testdata/ci/random.csv
      - name: Find set-based ODs using DISTOD
        run: mkdir -p data && java -Xms2g -Xmx2g -XX:+UseG1GC -Ddistod.input.path="./testdata/ci/random.csv" -Ddistod.input.has-header="no" -Dfile.encoding=UTF-8 -jar ./testdata/ci/distod.jar
      - name: Generate candidates
        run: python3 ./scripts/generate-all-candidates.py --path ./testdata/ci/candidates.txt
      - name: Validate candidates
        run: python3 ./scripts/validate-list-based-candidates.py -i ./testdata/ci/random.csv --valid-file ./testdata/ci/valid.txt --invalid-file ./testdata/ci/invalid.txt -c ./testdata/ci/candidates.txt
      - name: Test C# algorithm
        run: python3 ./scripts/test-algorithm.py --set-based-path ./data/results.txt --invalid-path ./testdata/ci/invalid.txt --valid-path ./testdata/ci/valid.txt --attributes-path ./testdata/ci/attributes.txt

  
  benchmark:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Benchmark
        run: dotnet run -c Release --project Benchmarks
